### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by thanh3d** [braedon/prometheus-es-exporter#20]
> prometheus-es-exporter -p 9206  -e http://localhost:9200 -c /opt/prometheus-es-exporter/exporter.cfg 
Traceback (most recent call last):
  File "/opt/prometheus-es-exporter/prometheus-es-exporter/bin/prometheus-es-exporter", line 7, in <module>
    from prometheus_es_exporter import main
  File "/opt/prometheus-es-exporter/prometheus-es-exporter/lib/python3.4/site-packages/prometheus_es_exporter/__init__.py", line 17, in <module>
    from prometheus_es_exporter import cluster_health_parser
  File "/opt/prometheus-es-exporter/prometheus-es-exporter/lib/python3.4/site-packages/prometheus_es_exporter/cluster_health_parser.py", line 34
    result.extend(parse_block(n_value, metric=metric + [key], labels={**labels, singular_key: [n_key]}))
                                                                       ^
SyntaxError: invalid syntax

Can you advise ?

**Comment by braedon** [comment]
Hi @thanh3d, looks like the syntax for unpacking a dictionary inside a dictionary display was only added in Python 3.5 (see [PEP 448](https://www.python.org/dev/peps/pep-0448/)).

I'll push a patch soon, but if you can upgrade your Python version to 3.5+ you can work around it in the meantime.

**Comment by braedon** [comment]
@thanh3d Released a fix in version 0.4.2. Let me know if you have further issues.
