### ISSUE TITLE
configparser.InterpolationSyntaxError if using regex with %

### ISSUE THREAD

**Issue by jangrewe** [braedon/prometheus-es-exporter#28]
Hi,
i've been building a query that includes a regex with `%` in it, which the configparser doesn't seem to like:

```
Traceback (most recent call last):
  File "/usr/local/bin/prometheus-es-exporter", line 11, in <module>
    load_entry_point('prometheus-es-exporter', 'console_scripts', 'prometheus-es-exporter')()
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 382, in main
    query = json.loads(config.get(section, 'QueryJson'))
  File "/usr/local/lib/python3.7/configparser.py", line 799, in get
    d)
  File "/usr/local/lib/python3.7/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/local/lib/python3.7/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%3[aA])[0-9]+|.+\\%40.+).*\'\n}\n}\n]\n}\n},\n"aggs": {\n"request": {\n"terms": {\n"field": "request_path",\n"size": 100\n},\n"aggs": {\n"response": {\n"terms": {\n"field": "response"\n}\n}\n}\n}\n}\n}'
```

The (simplified) config looks like this:
```
QueryJson = {
    "size": 0,
    "query": {
      "bool": {
        "must_not": [
          {
            "regexp": {
              "request_path": ".*(.+(\/|:|%3a)[0-9]+|.+%40.+).*"
            }
          }
        ]
      }
    }
```

**Comment by braedon** [comment]
Hi @jangrewe, this just sounds like part of the config syntax. Doesn't seem like a bug?
