### ISSUE TITLE
Can't aggregate by numeric field

### ISSUE THREAD

**Issue by Braedon** [Braedon/prometheus-es-exporter#8]
Bucket label generation expects string bucket names - throws an exception on numeric:
```Traceback (most recent call last):
  File "/usr/local/bin/prometheus-es-exporter", line 9, in <module>
    load_entry_point('prometheus-es-exporter', 'console_scripts', 'prometheus-es-exporter')()
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 135, in main
    scheduler.run()
  File "/usr/local/lib/python3.5/sched.py", line 147, in run
    action(*argument, **kwargs)
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 65, in scheduled_run
    update_gauges(metrics)
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 31, in update_gauges
    for key in label_keys
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 31, in <listcomp>
    for key in label_keys
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 16, in format_label_value
    return '_'.join(value_list).replace('.', '_')
TypeError: sequence item 1: expected str instance, int found
```

**Comment by Braedon** [comment]
https://github.com/Braedon/prometheus-es-exporter/pull/9
